### ISSUE TITLE
[❌ ] Failed to sign Snapchat.app with entitlements.xml. Check tweakpatcher.log for more information.

### ISSUE THREAD

**Issue by ToothyArmy** [Defying/TweakPatcher#4]
This comes up every time I try for the first time on an Apple ID. Then every time After it doesn't even try to download.

**Comment by liudayu** [comment]
Can you also show us the tweakpatcher.log file?

**Comment by Unknown-iOS** [comment]
[tweakpatcher.log.zip](https://github.com/Defying/TweakPatcher/files/211316/tweakpatcher.log.zip)
 This would help you.

**Comment by Defying** [comment]
post your tweakpatcher.log

@Unknown-iOS don't run the patcher with BUNDLE_ID at the end. that argument is for using an already existing provisioning profile (which BUNDLE_ID obviously doesn't exist)

**Comment by Unknown-iOS** [comment]
@Defying even if i don't run BUNDLE_ID i get the entitlememnts.xml error.

**Comment by Defying** [comment]
@Unknown-iOS post your tweakpatcher.log without the BUNDLE_ID

**Comment by ToothyArmy** [comment]
I am going to try again, I did not mean to use the BUNDLE_ID

**Comment by ToothyArmy** [comment]
Every since the first time I tried it, it has come up with this message.
https://gyazo.com/1e5434a18657b7cc154c7647df7099a8

**Comment by ToothyArmy** [comment]
http://pastebin.com/vqvib5Jr 
There is the tweakpatcher.log

**Comment by Defying** [comment]
@ToothyArmy have you pressed "Reset" on that Xcode error?

that should fix your issue. looking at your log, it can't find the cert

**Comment by ToothyArmy** [comment]
Yes, I have pressed Fix Issue many times.

**Comment by ToothyArmy** [comment]
I have clicked reset a few times, then it makes a new cert but the expiration date is the exact time that I clicked reset so I am not able to click Fix Issue after I click reset.

**Comment by HelpMepleaseSir** [comment]
i have the same error but im not sure how to fix it !!!

**Comment by HelpMepleaseSir** [comment]
[tweakpatcher.log.zip](https://github.com/Defying/TweakPatcher/files/211519/tweakpatcher.log.zip)
 That is my log if anyone can help

**Comment by Defying** [comment]
@HelpMepleaseSir (and anyone else with this issue)

try this experimental: https://github.com/Defying/TweakPatcher/archive/experimental.zip

**Comment by Defying** [comment]
everyone with this issue, try this experimental branch and see if it fixes it: https://github.com/Defying/TweakPatcher/archive/experimental.zip

**Comment by ArdieWijaya** [comment]
i have the same error!
here's my log 

[tweakpatcher.log.zip](https://github.com/Defying/TweakPatcher/files/211542/tweakpatcher.log.zip)

**Comment by Defying** [comment]
@ArdieWijaya try the experimental version linked above your post

**Comment by ArdieWijaya** [comment]
@Defying that still doesn't work! 
here's my new log from the experimental version
[tweakpatcher.log.zip](https://github.com/Defying/TweakPatcher/files/211544/tweakpatcher.log.zip)

**Comment by Defying** [comment]
@ArdieWijaya can you post the output of `ls .temp/Payload`?

**Comment by ArdieWijaya** [comment]
@Defying how to do that?

**Comment by Defying** [comment]
@ArdieWijaya type that into Terminal while you're in the TweakPatcher directory

**Comment by ArdieWijaya** [comment]
here's  the result 
![screen shot 2016-04-10 at 07 00 28](https://cloud.githubusercontent.com/assets/18372049/14407189/f310a090-fee9-11e5-9301-a48dd3197ef7.png)

**Comment by ArdieWijaya** [comment]
here's the result

![screen shot 2016-04-10 at 07 00 28](https://cloud.githubusercontent.com/assets/18372049/14407191/09cc9050-feea-11e5-9981-9e0e01b1b148.png)

**Comment by ArdieWijaya** [comment]
@Defying here's the result
![screen shot 2016-04-10 at 07 00 28](https://cloud.githubusercontent.com/assets/18372049/14407208/7f6cedfa-feea-11e5-812f-f208b6434fe0.png)

**Comment by Defying** [comment]
@ArdieWijaya looking at your log again, it looks like it's being caused by a certificate issue, not the patcher script

try this: 
1. Open "Keychain Access" on your Mac
2. Select "My Certificates" under "Category"
3. Delete any certificates beginning with "iPhone Developer"
4. Make a new project in Xcode
5. Press "Fix Issue". It will regenerate a new certificate.
6. Try running the patcher again.

**Comment by ArdieWijaya** [comment]
@Defying i still can't fix it

**Comment by Defying** [comment]
@ArdieWijaya what do you mean?

**Comment by ToothyArmy** [comment]
I will try it.

**Comment by ArdieWijaya** [comment]
@Defying i've tried to open keychain access, but still it doesn't work

**Comment by Defying** [comment]
@ArdieWijaya were you able to regenerate the certificate in Xcode?

**Comment by ToothyArmy** [comment]
This message still comes up. Yes I have clicked reset but then it creates a certificate that is set to expire the exact date of Today. So I go into KeyChain access and remove that certificate then I do it again and it does the same thing. 

https://gyazo.com/410a820b34a58f450c292f95159f408b

**Comment by ArdieWijaya** [comment]
@Defying yes i was able to regenerate it, then i've tried with the experimental version, and still doesn't work

**Comment by Defying** [comment]
@ToothyArmy the "iPhone Developer" certificate it generates shouldn't expire until 2017.. 

something is likely wrong with your Xcode/Apple ID.

---

@ArdieWijaya what's the expiration date on the new certificate it generates?

**Comment by ToothyArmy** [comment]
I have an Idea hope this works!

**Comment by ToothyArmy** [comment]
All I had to do was reset the certificate then close Xcode then open it again and redo the Xcode part.

**Comment by ToothyArmy** [comment]
Yes! It worked!

**Comment by ToothyArmy** [comment]
The Disable Screenshot Log does not work.

**Comment by ToothyArmy** [comment]
Once you reset your certificate redo the whole process and it should work.

**Comment by ArdieWijaya** [comment]
@Defying April 10, 2017

**Comment by ToothyArmy** [comment]
@ArdieWijaya once you reset your certificate, restart the whole process and it should work. That is what I did and it worked.

**Comment by jordanotsuji** [comment]
[tweakpatcher.log.zip](https://github.com/Defying/TweakPatcher/files/211655/tweakpatcher.log.zip)
please help me fix my problem. [❌ ] Failed to install Snapchat.ipa to iOS device. Check tweakpatcher.log for more information. @Defying

**Comment by Jwiggiff** [comment]
I had this same problem but I fixed it. When you make the Xcode project at the top after you select your device make sure the bar at the top fully loads then it worked for me

**Comment by AbsenteBill** [comment]
I've tried 3 times and I still have the same problem what do I do?

**Comment by ToothArmy** [comment]
@AbsenteBill what is the problem you are having?

**Comment by nobbykaonza-oss** [comment]
this is how i fixed it, when you go to keychain access, when your iphone is connected, head over to certificates. you will see 4 certificates, take not off them all then proceed to delete them. how ever you will notice that one certificate will come back, do not delete that certificate, instead go back to xcode and it set it up again and you will still see the "fix issue" button still there. the only difference is that this time instead of prompting you to reset the original certificates, it is aware of that one certificate so it lets you go right on through. you should have no issues what so ever now. if you need me to send my log just ask

**Comment by len2307** [comment]
send log please

**Comment by cthulhu91** [comment]
Still having a tough time getting past this...
[tweakpatcher.log.zip](https://github.com/Defying/TweakPatcher/files/213413/tweakpatcher.log.zip)

**Comment by Defying** [comment]
@cthulhu91 you're missing your iPhone Developer certificate:

```
[✒️ ] Codesigning .dylib dependencies with certificate ""
: no identity found
: no identity found
: no identity found
: no identity found
: no identity found
: no identity found
: no identity found
: no identity found
: no identity found
```

**Comment by hooplaa** [comment]
I get the same message here is my log

[tweakpatcher.log.zip](https://github.com/Defying/TweakPatcher/files/213679/tweakpatcher.log.zip)

**Comment by hooplaa** [comment]
also when the error pops up i get an email saying my iOS Development certificate has been revoked

**Comment by ToothyArmy** [comment]
I got that too but it didn't change anything I just had to reset my certificate

**Comment by hooplaa** [comment]
@ToothyArmy how do you reset it?

**Comment by hooplaa** [comment]
nvm i just restarted my mac and it worked

**Comment by Ohhmyswag** [comment]
i got same error. my certificate is valid and i try all helpmeet please
[tweakpatcher.txt](https://github.com/Defying/TweakPatcher/files/213843/tweakpatcher.txt)

**Comment by cthulhu91** [comment]
just re downloaded the tweak patcher with updated link. everything worked fine.

**Comment by ToothyArmy** [comment]
What I did when my certificate didn't work is once I clicked fix issue it would ask if I wanted to reset and I would reset it then restart the whole process.

**Comment by Mad-Madam-Mim** [comment]
Hey everyone!!!! I had this super irritating issue as well and I fixed it for myself. 

First off, delete everything you've done. Delete the tweak patcher master file on desktop, empty trash, quit terminal, quit Xcode and any other apps you may have open. Then go to Keychain and delete certificates (a new certificate will appear, keep this one). Now start over, download cracked snapchat from Vshare and everything else and when you get to opening Xcode, go to Xcode>preferences>accounts>select the account you will use>view details> under signing identities if you can press reset on any, reset them> under provisioning profiles, move them all to the trash. After this is done continue as usual. Hope this works for you all!

**Comment by felixhas** [comment]
I've got the same problem as @Ohhmyswag .
I tried to delete all certificates, but I still got the message "[❌ ] Failed to sign Snapchat.app with entitlements.xml" in the terminal.
The tweakpatcher.log says:
"ls: .temp/Payload/Snapchat.app/PlugIns/com._/com._: No such file or directory
ls: .temp/Payload/Snapchat.app/PlugIns/com._: No such file or directory
ls: .temp/Payload/Snapchat.app/Frameworks/_: No such file or directory".
Does anybody knows a solution for my problem?

**Comment by ToothArmy** [comment]
When you click fix issue does a little drop down thing come up and say "cancel" then "reset"? If so click reset then restart the whole process. If the drop down thing doesn't come up go to your certificates and delete all of them. And I mean ALL of them then try again.

**Comment by nobbykaonza-oss** [comment]
you dont delete all your certificates

**Comment by felixhas** [comment]
yes, i have deleted all of my certificates. Then on xcode there was this drop down thing where i clicked reset. But it still says me "[❌ ] Failed to sign Snapchat.app with entitlements.xml. Check tweakpatcher.log for more information.". I have tried it with deleting the new certificate, i have tried it with running this process again with the new certificate but every time i get this error. So the solutions from the troubleshooting page are not working for me.

**Comment by ToothyArmy** [comment]
Once you click reset and get your new certificate close xcode and restart it

**Comment by felixhas** [comment]
This didn't work, too. I have clicked on reset and restarted xcode but the error is still the same

**Comment by Mad-Madam-Mim** [comment]
You also have to delete your provisioning profiles 

-Cal

**Comment by Mad-Madam-Mim** [comment]
YOU HAVE TO DELETE PROVISIONING PROFILES

-Cal

**Comment by felixhas** [comment]
I don't get it, I have deleted all of the provisioning profiles, I have deleted all of my certificates, I have created a new certificate by clicking reset in the drop down menu, I have restarted xcode and the terminal but I still get the error. The tweakpatcher.log says "iPhone Developer: xxxx@xxxx.com (37YRLAALAE) : no identity found". This happens every time, even when I try your solutions.

**Comment by Jwiggiff** [comment]
Try deleting every thing. All provisioning profiles, all certificates, tweakpatcher and snapchat ipa. Then re download everything and try sgain

**Comment by Mad-Madam-Mim** [comment]
Try signing out of Your Apple ID on your phone? Try making a new one on the computer?

-Cal

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
